//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_MySet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean MyAddPin
        {
            get
            {
                return SteamVR_Actions.mySet_MyAddPin;
            }
        }
        
        public virtual SteamVR_Action_Boolean MyMoveMap
        {
            get
            {
                return SteamVR_Actions.mySet_MyMoveMap;
            }
        }
        
        public virtual SteamVR_Action_Boolean MyRorateMap
        {
            get
            {
                return SteamVR_Actions.mySet_MyRorateMap;
            }
        }
        
        public virtual SteamVR_Action_Boolean MyZoomMap
        {
            get
            {
                return SteamVR_Actions.mySet_MyZoomMap;
            }
        }
    }
}
